FROM nvcr.io/nvidia/pytorch:24.06-py3

RUN pip install gpustat
RUN pip install transformers==4.45.2
RUN pip install datasets==3.0.1
RUN pip install sentencepiece==0.2.0
RUN pip install accelerate==1.0.1
RUN pip install lm_eval==0.4.5
